/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kenvix_android_ApplicationEnvironment_UserApplication */

#ifndef _Included_com_kenvix_android_ApplicationEnvironment_UserApplication
#define _Included_com_kenvix_android_ApplicationEnvironment_UserApplication
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
