/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kenvix_android_ApplicationEnvironment_Utils */

#ifndef _Included_com_kenvix_android_ApplicationEnvironment_Utils
#define _Included_com_kenvix_android_ApplicationEnvironment_Utils
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
